allowBuilds:
  '@reown/appkit': true
  bufferutil: true
  keccak: true
  node-libcurl: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
blockExoticSubdeps: false
